# Generated by Django 4.2.14 on 2024-08-02 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_comment"),
        ("users", "0006_customuser_first_name_en_customuser_first_name_ru_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "less",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        related_name="less_recommended",
                        to="articles.topic",
                    ),
                ),
                (
                    "more",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        related_name="more_recommended",
                        to="articles.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "db_table": "recommendation",
                "ordering": ["-created_at"],
            },
        ),
    ]
