# Generated by Django 4.2.14 on 2024-08-02 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_follows",
                        to="articles.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Follow",
                "verbose_name_plural": "Topic Follows",
                "db_table": "topic_follow",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="topicfollow",
            constraint=models.UniqueConstraint(
                fields=("user", "topic"), name="unique_user_topic"
            ),
        ),
    ]
