# Generated by Django 4.2.14 on 2024-08-02 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_pin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pin",
        ),
    ]
